name: S12 - IaC & Container Security
on:
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile'
      - 'iac/**'
      - 'requirements.txt'
      - '.github/workflows/ci-s12-iac-container.yml'
jobs:
  s12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure evidence dirs
        run: mkdir -p EVIDENCE/S12

      - name: Build image
        run: docker build -t s09s12-app:ci .

      - name: Test container health check
        run: |
          # Run container
          docker run -d --name health-test s09s12-app:ci
          
          # Wait for health checks to run (need multiple intervals)
          echo "Waiting for health checks to run..."
          sleep 45
          
          # Get the health status in your desired format
          docker inspect --format='{{json .State.Health}}' health-test > EVIDENCE/S12/health_status.json
          
          # Also check current status
          echo "Current container status:"
          docker ps -a | grep health-test
          
          # Clean up
          docker stop health-test
          docker rm health-test
          
          # Show the generated health file
          cat EVIDENCE/S12/health_status.json

      - name: Hadolint Dockerfile (JSON)
        run: |
          docker run --rm -i hadolint/hadolint hadolint -f json - < Dockerfile > EVIDENCE/S12/hadolint.json

      - name: Checkov (iac/)
        run: |
          docker run --rm -v $PWD:/src bridgecrew/checkov:latest -d /src/iac -o json > EVIDENCE/S12/checkov.json 
        continue-on-error: true

      - name: Trivy image (JSON)
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/work aquasec/trivy:latest image --format json --output /work/EVIDENCE/S12/trivy.json --ignore-unfixed s09s12-app:ci --severity HIGH,CRITICAL --exit-code 1

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: S12_EVIDENCE
          path: EVIDENCE/S12